projects:
  - name: Piano nazionale di digitalizzazione del patrimonio culturale
    description: 
      descrizione del piano [...]
    documents:
      - project-document-doc
      - another-project-document-doc
    short_name: PND
    website: https://digitallibrary.cultura.gov.it
    tags:
      - digitalization
      - cultural heritage
      - 
