projec ts:
  - name: Piano nazionale di digitalizzazione del patrimonio culturale
    description: | 
      Il PND costituisce la visione strategica con la quale il Ministero della Cultura intende promuovere e organizzare il processo di trasformazione digitale nel quinquennio 2022-2026.
      Il piano si ri  volge ai musei, agli archivi, alle biblioteche, agli istituti centrali e ai luoghi della cultura statali che conservano, gestiscono e valorizzano i beni culturali.
    documents:
      - PND-docs
    short_name: PND
    website: https://digitallibrary.cultura.gov.it
    tags:
      - patrimonio culturale digitale
      - digitalizzazione
      - digital transformation
