publisher:
  name: Ministero della Cultura, Istituto centrale per la digitalizzazione del patrimonio culturale - DIGITAL LIBRARY
  description: |
    descrizione [...]
  github_organization_url: github.com/ICDP-Digital-Library
  short_name: ICDP-DL
  website: https://digitallibrary.cultura.gov.it/
  tags:
    - cultural heritage
    - digitalization
    - ...
  logo: assets/images/logo.svg
